import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'uz' | 'ru' | 'en';

interface LangCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  uz: {
    // Navbar
    'nav.features': 'Imkoniyatlar',
    'nav.how': 'Qanday ishlaydi',
    'nav.pricing': 'Narxlar',
    'nav.start': 'Boshlash',

    // Hero
    'hero.badge': 'Savdo uchun aqlli daftar',
    'hero.title1': 'Savdoni',
    'hero.title2': 'osonlashtiring',
    'hero.desc': "Daftarni tashlang — Savdo avtomatik hisoblaydi. Mahsulotlar, sotuvlar, foyda va hisobotlar bir joyda.",
    'hero.cta': 'Bepul boshlash',
    'hero.demo': "Demo ko'rish",
    'hero.today': 'Bugungi savdo',
    'hero.sum': "so'm",
    'hero.profit': 'Foyda',
    'hero.sales': 'Sotuvlar',
    'hero.products': 'Tovarlar',
    'hero.traders': 'Savdogarlar',
    'hero.accounts': 'Hisoblar',
    'hero.rating': 'Baho',

    // Problems
    'problems.badge': 'Muammo',
    'problems.title': 'Kundalik muammolar',
    'problems.desc': "Ko'pchilik savdogarlar hali ham eski usulda ishlaydi",
    'problems.1.title': 'Daftarda yozish',
    'problems.1.desc': "Har kuni yozib, hisoblash vaqt oladi",
    'problems.2.title': "Xatolar ko'p",
    'problems.2.desc': "Qo'lda hisoblashda doimo xatolik",
    'problems.3.title': "Vaqt yo'qoladi",
    'problems.3.desc': "Oylik hisobga soatlab vaqt ketadi",
    'problems.4.title': "Tovar yo'qoladi",
    'problems.4.desc': "Qoldiqni kuzatmaslik — zarar",
    'problems.solution': 'Yechim bor',

    // Features
    'features.badge': 'Imkoniyatlar',
    'features.title': 'Hamma narsa bir joyda',
    'features.desc': "Oddiy va aqlli — hamma hisob-kitobni siz uchun qiladi",
    'features.1.title': "Tovar qo'shish",
    'features.1.desc': "Nomi, narxi, miqdorini kiriting — hamma narsa saqlanadi",
    'features.2.title': 'Sotuv qilish',
    'features.2.desc': "Tovarni tanlang, foyda va qoldiq avtomatik hisoblanadi",
    'features.3.title': 'Hisobotlar',
    'features.3.desc': "Kunlik va oylik hisobotlar bir qarashda ko'ring",
    'features.4.title': 'Foyda hisoblash',
    'features.4.desc': "Har bir sotuvdan foydani avtomatik ko'ring",
    'features.5.title': 'Bildirishnomalar',
    'features.5.desc': "Tovar kamayib qolganda xabar olasiz",
    'features.6.title': 'Oddiy interfeys',
    'features.6.desc': "Katta tugmalar, oddiy til — xuddi daftardek",

    // How it works
    'how.badge': 'Qanday ishlaydi',
    'how.title': '4 oddiy qadam',
    'how.desc': "Hech qanday murakkab sozlash yo'q",
    'how.1.title': "Ro'yxatdan o'ting",
    'how.1.desc': "Telefon raqam + SMS kod. 30 soniyada tayyor!",
    'how.2.title': "Tovarlarni qo'shing",
    'how.2.desc': "Nomi, narxi, miqdorini kiriting",
    'how.3.title': 'Sotuvlarni yozing',
    'how.3.desc': "Tanlang, miqdor kiriting — foyda avtomatik",
    'how.4.title': "Hisobotni ko'ring",
    'how.4.desc': "Foyda, sotuvlar, xarajatlar — barchasi",

    // Pricing
    'pricing.badge': 'Narxlar',
    'pricing.title': 'Oddiy va qulay',
    'pricing.desc': "Bepul boshlang, biznesingiz bilan birga o'sing",
    'pricing.free': 'Bepul',
    'pricing.freeNote': 'Doim bepul',
    'pricing.month': "so'm / oy",
    'pricing.popular': 'Eng mashhur',
    'pricing.startFree': 'Bepul boshlash',
    'pricing.choose': 'Tanlash',
    'pricing.s.1': '30 tagacha tovar',
    'pricing.s.2': 'Sotuvlarni yozish',
    'pricing.s.3': 'Kunlik hisobot',
    'pricing.s.4': 'Oylik hisobot',
    'pricing.s.5': 'Excel eksport',
    'pricing.p.1': 'Cheksiz tovarlar',
    'pricing.p.2': 'Kunlik + Oylik hisobot',
    'pricing.p.3': 'Excel eksport',
    'pricing.p.4': 'Oddiy interfeys',
    'pricing.p.5': 'Telegram bot',
    'pricing.pr.1': 'Hammasi Pro dan',
    'pricing.pr.2': 'Narx tarixi',
    'pricing.pr.3': 'Kengaytirilgan hisobot',
    'pricing.pr.4': 'Ustunlik support',
    'pricing.pr.5': 'API integratsiya',

    // Testimonials
    'testimonials.badge': 'Fikrlar',
    'testimonials.title': 'Savdogarlar nima deydi',
    'testimonials.1.text': "Avval daftarda yozardim. Endi Savdo hammasi avtomatik. Bir oyda 200,000 so'm ko'proq foyda topdim!",
    'testimonials.1.name': 'Aziz Karimov',
    'testimonials.1.role': 'Chorsu, meva-savzavot',
    'testimonials.2.text': "50 yoshdaman, ilova ishlatishni bilmasdim. Savdo juda oddiy — 5 daqiqada o'rganib oldim!",
    'testimonials.2.name': 'Nilufar R.',
    'testimonials.2.role': 'Malika, kiyim-kechak',
    'testimonials.3.text': "Qaysi tovar ko'p foyda keltirayotganini ko'raman. Endi savdo qilish aqlli bo'ldi!",
    'testimonials.3.name': 'Botir Umarov',
    'testimonials.3.role': 'Yunusobod, oziq-ovqat',

    // CTA
    'cta.badge': 'Bepul boshlang',
    'cta.title': 'Savdoingizni bugundan raqamlashtiring',
    'cta.desc': "30 soniyada ro'yxatdan o'ting va savdo qilishni boshlang",
    'cta.btn': 'Bepul boshlash',
    'cta.noCard': 'Karta shart emas',
    'cta.fast': '30s tayyor',

    // Footer
    'footer.desc': "Oddiy, aqlli daftar. Savdogarlar uchun, savdogarlar tomonidan yaratilgan.",
    'footer.pages': 'Sahifalar',
    'footer.contact': "Bog'lanish",
    'footer.privacy': 'Maxfiylik',
    'footer.terms': 'Shartlar',
    'footer.social': 'Ijtimoiy tarmoqlar',
    'footer.newsletter': 'Yangiliklar',
    'footer.newsletter.desc': "Yangi imkoniyatlar haqida birinchi bo'lib biling",
    'footer.newsletter.placeholder': 'Email manzilingiz',
    'footer.newsletter.btn': "Obuna bo'lish",
  },

  ru: {
    'nav.features': 'Возможности',
    'nav.how': 'Как работает',
    'nav.pricing': 'Цены',
    'nav.start': 'Начать',

    'hero.badge': 'Умная тетрадь для торговли',
    'hero.title1': 'Упрощайте',
    'hero.title2': 'торговлю',
    'hero.desc': 'Забудьте про тетрадь — Savdo считает автоматически. Товары, продажи, прибыль и отчёты в одном месте.',
    'hero.cta': 'Начать бесплатно',
    'hero.demo': 'Смотреть демо',
    'hero.today': 'Сегодняшние продажи',
    'hero.sum': 'сум',
    'hero.profit': 'Прибыль',
    'hero.sales': 'Продажи',
    'hero.products': 'Товары',
    'hero.traders': 'Продавцы',
    'hero.accounts': 'Расчёты',
    'hero.rating': 'Оценка',

    'problems.badge': 'Проблема',
    'problems.title': 'Ежедневные проблемы',
    'problems.desc': 'Большинство продавцов всё ещё работают по-старому',
    'problems.1.title': 'Запись в тетрадь',
    'problems.1.desc': 'Писать и считать каждый день — долго',
    'problems.2.title': 'Много ошибок',
    'problems.2.desc': 'Ручной расчёт всегда приводит к ошибкам',
    'problems.3.title': 'Время теряется',
    'problems.3.desc': 'На месячный отчёт уходят часы',
    'problems.4.title': 'Товар теряется',
    'problems.4.desc': 'Без контроля остатков — убытки',
    'problems.solution': 'Есть решение',

    'features.badge': 'Возможности',
    'features.title': 'Всё в одном месте',
    'features.desc': 'Простой и умный — все расчёты за вас',
    'features.1.title': 'Добавление товара',
    'features.1.desc': 'Введите название, цену, количество — всё сохраняется',
    'features.2.title': 'Продажа',
    'features.2.desc': 'Выберите товар, прибыль и остаток считаются автоматически',
    'features.3.title': 'Отчёты',
    'features.3.desc': 'Дневные и месячные отчёты одним взглядом',
    'features.4.title': 'Расчёт прибыли',
    'features.4.desc': 'Автоматический расчёт прибыли с каждой продажи',
    'features.5.title': 'Уведомления',
    'features.5.desc': 'Получите уведомление когда товар заканчивается',
    'features.6.title': 'Простой интерфейс',
    'features.6.desc': 'Большие кнопки, простой язык — как тетрадь',

    'how.badge': 'Как работает',
    'how.title': '4 простых шага',
    'how.desc': 'Никаких сложных настроек',
    'how.1.title': 'Зарегистрируйтесь',
    'how.1.desc': 'Телефон + СМС код. Готово за 30 секунд!',
    'how.2.title': 'Добавьте товары',
    'how.2.desc': 'Введите название, цену, количество',
    'how.3.title': 'Записывайте продажи',
    'how.3.desc': 'Выберите, введите количество — прибыль автоматически',
    'how.4.title': 'Смотрите отчёты',
    'how.4.desc': 'Прибыль, продажи, расходы — всё наглядно',

    'pricing.badge': 'Цены',
    'pricing.title': 'Просто и удобно',
    'pricing.desc': 'Начните бесплатно, растите вместе с бизнесом',
    'pricing.free': 'Бесплатно',
    'pricing.freeNote': 'Навсегда бесплатно',
    'pricing.month': 'сум / мес',
    'pricing.popular': 'Самый популярный',
    'pricing.startFree': 'Начать бесплатно',
    'pricing.choose': 'Выбрать',
    'pricing.s.1': 'До 30 товаров',
    'pricing.s.2': 'Запись продаж',
    'pricing.s.3': 'Дневной отчёт',
    'pricing.s.4': 'Месячный отчёт',
    'pricing.s.5': 'Экспорт в Excel',
    'pricing.p.1': 'Безлимит товаров',
    'pricing.p.2': 'Дневной + Месячный отчёт',
    'pricing.p.3': 'Экспорт в Excel',
    'pricing.p.4': 'Простой интерфейс',
    'pricing.p.5': 'Telegram бот',
    'pricing.pr.1': 'Всё из Pro',
    'pricing.pr.2': 'История цен',
    'pricing.pr.3': 'Расширенные отчёты',
    'pricing.pr.4': 'Приоритетная поддержка',
    'pricing.pr.5': 'API интеграция',

    'testimonials.badge': 'Отзывы',
    'testimonials.title': 'Что говорят продавцы',
    'testimonials.1.text': 'Раньше записывал в тетрадь. Теперь Savdo всё автоматически. За месяц нашёл на 200,000 сум больше прибыли!',
    'testimonials.1.name': 'Азиз Каримов',
    'testimonials.1.role': 'Чорсу, фрукты-овощи',
    'testimonials.2.text': 'Мне 50 лет, не умела пользоваться приложениями. Savdo очень простой — освоила за 5 минут!',
    'testimonials.2.name': 'Нилуфар Р.',
    'testimonials.2.role': 'Малика, одежда',
    'testimonials.3.text': 'Вижу какой товар приносит больше прибыли. Теперь торговля стала умной!',
    'testimonials.3.name': 'Ботир Умаров',
    'testimonials.3.role': 'Юнусабад, продукты',

    'cta.badge': 'Начните бесплатно',
    'cta.title': 'Оцифруйте торговлю уже сегодня',
    'cta.desc': 'Зарегистрируйтесь за 30 секунд и начните торговать',
    'cta.btn': 'Начать бесплатно',
    'cta.noCard': 'Карта не нужна',
    'cta.fast': 'Готово за 30с',

    'footer.desc': 'Простая, умная тетрадь. Создана продавцами для продавцов.',
    'footer.pages': 'Страницы',
    'footer.contact': 'Контакты',
    'footer.privacy': 'Конфиденциальность',
    'footer.terms': 'Условия',
    'footer.social': 'Соцсети',
    'footer.newsletter': 'Рассылка',
    'footer.newsletter.desc': 'Узнайте о новых возможностях первыми',
    'footer.newsletter.placeholder': 'Ваш email',
    'footer.newsletter.btn': 'Подписаться',
  },

  en: {
    'nav.features': 'Features',
    'nav.how': 'How it works',
    'nav.pricing': 'Pricing',
    'nav.start': 'Get started',

    'hero.badge': 'Smart notebook for traders',
    'hero.title1': 'Simplify your',
    'hero.title2': 'trading',
    'hero.desc': 'Ditch the notebook — Savdo calculates automatically. Products, sales, profit and reports in one place.',
    'hero.cta': 'Start free',
    'hero.demo': 'View demo',
    'hero.today': "Today's sales",
    'hero.sum': "so'm",
    'hero.profit': 'Profit',
    'hero.sales': 'Sales',
    'hero.products': 'Products',
    'hero.traders': 'Traders',
    'hero.accounts': 'Calculations',
    'hero.rating': 'Rating',

    'problems.badge': 'Problem',
    'problems.title': 'Daily problems',
    'problems.desc': 'Most traders still work the old-fashioned way',
    'problems.1.title': 'Writing in notebooks',
    'problems.1.desc': 'Writing and calculating daily takes too long',
    'problems.2.title': 'Too many errors',
    'problems.2.desc': 'Manual calculations always lead to mistakes',
    'problems.3.title': 'Time wasted',
    'problems.3.desc': 'Monthly reports take hours to prepare',
    'problems.4.title': 'Stock gets lost',
    'problems.4.desc': 'No stock tracking means losses',
    'problems.solution': 'There is a solution',

    'features.badge': 'Features',
    'features.title': 'Everything in one place',
    'features.desc': 'Simple and smart — does all the math for you',
    'features.1.title': 'Add products',
    'features.1.desc': 'Enter name, price, quantity — everything is saved',
    'features.2.title': 'Make sales',
    'features.2.desc': 'Select a product, profit and stock calculated automatically',
    'features.3.title': 'Reports',
    'features.3.desc': 'Daily and monthly reports at a glance',
    'features.4.title': 'Profit calculation',
    'features.4.desc': 'Automatic profit calculation from every sale',
    'features.5.title': 'Notifications',
    'features.5.desc': 'Get notified when stock is running low',
    'features.6.title': 'Simple interface',
    'features.6.desc': 'Big buttons, simple language — just like a notebook',

    'how.badge': 'How it works',
    'how.title': '4 simple steps',
    'how.desc': 'No complicated setup needed',
    'how.1.title': 'Sign up',
    'how.1.desc': 'Phone + SMS code. Ready in 30 seconds!',
    'how.2.title': 'Add products',
    'how.2.desc': 'Enter name, price, quantity',
    'how.3.title': 'Record sales',
    'how.3.desc': 'Select, enter quantity — profit is automatic',
    'how.4.title': 'View reports',
    'how.4.desc': 'Profit, sales, expenses — everything at a glance',

    'pricing.badge': 'Pricing',
    'pricing.title': 'Simple and fair',
    'pricing.desc': 'Start free, grow with your business',
    'pricing.free': 'Free',
    'pricing.freeNote': 'Always free',
    'pricing.month': "so'm / mo",
    'pricing.popular': 'Most popular',
    'pricing.startFree': 'Start free',
    'pricing.choose': 'Choose',
    'pricing.s.1': 'Up to 30 products',
    'pricing.s.2': 'Record sales',
    'pricing.s.3': 'Daily report',
    'pricing.s.4': 'Monthly report',
    'pricing.s.5': 'Excel export',
    'pricing.p.1': 'Unlimited products',
    'pricing.p.2': 'Daily + Monthly report',
    'pricing.p.3': 'Excel export',
    'pricing.p.4': 'Simple interface',
    'pricing.p.5': 'Telegram bot',
    'pricing.pr.1': 'Everything from Pro',
    'pricing.pr.2': 'Price history',
    'pricing.pr.3': 'Advanced reports',
    'pricing.pr.4': 'Priority support',
    'pricing.pr.5': 'API integration',

    'testimonials.badge': 'Reviews',
    'testimonials.title': 'What traders say',
    'testimonials.1.text': "Used to write in a notebook. Now Savdo does everything automatically. Found 200,000 so'm more profit in a month!",
    'testimonials.1.name': 'Aziz Karimov',
    'testimonials.1.role': 'Chorsu, fruits & vegetables',
    'testimonials.2.text': "I'm 50 years old, didn't know how to use apps. Savdo is so simple — learned in 5 minutes!",
    'testimonials.2.name': 'Nilufar R.',
    'testimonials.2.role': 'Malika, clothing',
    'testimonials.3.text': 'I can see which product brings the most profit. Trading is smart now!',
    'testimonials.3.name': 'Botir Umarov',
    'testimonials.3.role': 'Yunusobod, food',

    'cta.badge': 'Start for free',
    'cta.title': 'Digitize your trading today',
    'cta.desc': 'Sign up in 30 seconds and start selling',
    'cta.btn': 'Start free',
    'cta.noCard': 'No card required',
    'cta.fast': 'Ready in 30s',

    'footer.desc': 'Simple, smart notebook. Made by traders for traders.',
    'footer.pages': 'Pages',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.social': 'Social',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Be the first to know about new features',
    'footer.newsletter.placeholder': 'Your email',
    'footer.newsletter.btn': 'Subscribe',
  },
};

const LangContext = createContext<LangCtx>({ lang: 'uz', setLang: () => {}, t: (k) => k });

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem('savdo-lang') as Lang) || 'uz';
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('savdo-lang', l);
  };

  const t = (key: string) => translations[lang][key] || key;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
